{
   model: "ElasticRank",
   log_name: "ElasticRank-steam-mf",
   topk: [5, 10, 20],
   fairness_metrics: ['EF', "MMF", "Entropy"],
   fairness_type: "Utility", # ["Exposure", "Utility"], where Exposure only computes the exposure of item group while utility computes the ranking score of item groups
   ranking_store_path: "steam_mf", ##the ranking score stored path for the re-ranking, only re-ranking should change the value


   ###ElasticRank parameters
   t: 1.05,
   anchor_rate: 0.8,

}